# Task 3.8
places = ['Hanoi', 'Saigon', 'Danang', 'Nha Trang', 'Spain']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
# Task 3.9
places.append('Seoul')
print(places)
places.insert(2,'Tokyo')
del(places[5])
print(places)
places.pop()
print(places)
places.pop(1)
print(places)
places.remove('Spain')
print(places)
places[1] = 'Hoi An'
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)